development:
  adapter: postgresql
  encoding: unicode
  database: flashcards_development
  host: localhost
  pool: 5
  username: <%= ENV["APP_USERNAME"] %>
  password: <%= ENV["APP_PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: flashcards_test
  host: localhost
  pool: 5
  username: <%= ENV["APP_USERNAME"] %>
  password: <%= ENV["APP_PASSWORD"] %>

production:
  adapter: postgresql
  encoding: unicode
  database: flashcards_production
  host: localhost
  pool: 5
  username: <%= ENV["APP_USERNAME"] %>
  password: <%= ENV["APP_PASSWORD"] %>
