development:
  adapter: postgresql
  encoding: unicode
  database: flashcards_development
  pool: 5
  username: <%= ENV["APP_USERNAME"] %>

production:
  adapter: postgresql
  database: flashcards_production
  pool: 5
  username: <%= ENV["APP_USERNAME"] %>
